### ISSUE TITLE
Feature Request: Add a method to copy the original native hash

### ISSUE THREAD

**Issue by Yimura** [DottieDot/GTAV-NativeDB#11]
Currently I have to manually highlight the original native hash.

Take for example the following native
```cpp
// 0xC4BB298BD441BE78 0xE38A3AD4 b323
int SYSTEM::START_NEW_SCRIPT_WITH_NAME_HASH_AND_ARGS(Hash scriptHash, Any* args, int argCount, int stackSize);
```

It would be nice whenever I click the `0xC4BB298BD441BE78` it would automatically copy to clipboard.

My reasoning behind this feature request, I have had to highlight and copy a lot of native hashes manually.

**Comment by DottieDot** [comment]
Would you be able to elaborate on the use case? A workflow that only involves the native hash seems quite foreign to me. Is it for (or related to) ScriptHookV.NET development?

**Comment by Yimura** [comment]
I'm developing a mod menu for GTA V and I am hooking natives in scripts.

For this I'm using the original native hash to match in my crossmap and then detour hook to my native detour function.

It's not really an issue for me, more of just a quality of life rather.

Reference to the code in question since my menu is opensource:
https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/native_hooks/native_hooks.hpp#L25-L28

**Comment by DottieDot** [comment]
I've added the ability to click on the native hashes to copy them to your clipboard. Not 100% sure I like the implementation so I might revert/change the feature later depending on feedback.

**Comment by Yimura** [comment]
Sure thank you for considering my selfish request!
