### ISSUE TITLE
Bug (?): Copying the native and pasting it causes unicode issue

### ISSUE THREAD

**Issue by Yimura** [DottieDot/GTAV-NativeDB#12]
Whenever I copy a native from the site and paste it in one of my projects it will cause a unicode saving issue since the characters on the site are unicode text. Microsoft Visual Studio

Take for example when I copy the native from Fivem Native Reference I don't get this issue.

Screenshot:
![Unicode Issue](https://user-images.githubusercontent.com/24669514/151530542-0632c13e-c4e5-4326-b1bf-cb4052a558a1.png)

Save with other encodings:
![MSVS Save with other encodings](https://user-images.githubusercontent.com/24669514/151530655-8f28d003-4e8a-44c2-8296-ba0931ab8d09.png)
Windows-1252 encoding is an extension of the iso-8859-1 encoding which is single byte encoded opposed to unicode which uses 2.

Possible methods of fixing this:
 - Make a button that copies the native to clipboard (namespace + native), you shouldn't have to worry about encoding then of the website
 - Change encoding of content paint, unsure if this is feasible (?)

**Comment by DottieDot** [comment]
Thanks for reporting this issue. I was somewhat aware that this happens, but I didn't realize it is something that Visual Studio complains about.

> Make a button that copies the native to clipboard (namespace + native), you shouldn't have to worry about encoding then of the website

This is the easiest solution, but I'm not sure if it's ideal.  

As for changing the encoding, the Unicode characters in question are zero-width spaces that tell the browser where to wrap the text to prevent overflow. So removing these would cause problems with the page layout.

The best solution would probably be to use the [copy event](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event) to remove Unicode characters when the text is copied.

**Comment by DottieDot** [comment]
Fixed this while implementing #11. As mentioned in that thread I might revert/change it in the future depending on feedback.
