### ISSUE TITLE
Directly linking to natives doesn't work.

### ISSUE THREAD

**Issue by Yimura** [DottieDot/GTAV-NativeDB#16]
When linking a user to a native, https://nativedb.pieceof.art/natives/0x419594E137637120, for example. They won't be able to see anything useful if they haven't visited the site before.

To reproduce:
 1. Wipe Site Cache
 2. Visit direct link to native
 3. Get the 404 error from the underlying server

Additional info:
 - Docker build
 - Static production env

**Comment by DottieDot** [comment]
The web server has to be set up to redirect everything with no file extension to `/`.

**Comment by Yimura** [comment]
Ye probably a docker issue, I realised this later this week. Will look at reconfiguring nginx to redirect to /.
