### ISSUE TITLE
Cannot switch languages in Generate Code

### ISSUE THREAD

**Issue by JajarGaming** [DottieDot/GTAV-NativeDB#65]
If you try to change the language in Generate Code it brings you back and doesn't do anything - even for supported langs like TS

**Comment by DottieDot** [comment]
Thanks for reporting!

It looks like I forgot to update the [GenerateCodePage.tsx](https://github.com/DottieDot/GTAV-NativeDB/blob/30d876793170c97489d1bfd5a578a9306284b2b0/src/pages/GenerateCodePage/GenerateCodePage.tsx#L16) when I merged the two nativedbs into a single app. I'll try to fix this later tonight.
